### ISSUE TITLE
Failed deploy on temporal-srv-worker

### ISSUE THREAD

**Issue by bkniffler** [sw-yx/temporal-render#5]
Attempting to deploy after forking, all services are good except for temporal-srv-worker unfortunately.

<img width="993" alt="Bildschirmfoto 2022-02-14 um 09 36 04" src="https://user-images.githubusercontent.com/4349324/153828412-22a3001f-972c-4cb4-82b5-74a642ff1a68.png">

Any ideas why this might happen @sw-yx ? Thanks :)

**Comment by swyxio** [comment]
responded sending him to https://github.com/temporalio/temporal-render-simple for now. known issue, no time to solve
